from config import openai_client

def improve_description_with_llm(description, tags):
    """
    Enhances a raw imagge description using a language model and associated image tags.

    This function takes a basic description generated by an image analysis service,
    along with a list of image tags that include confidence scores, and uses a 
    language model GPT-4o-mini to generate a longer description of the image.

    Parameters:
        description (str): the initial raw description of the image.
        tags (list): a list of tag dictionaries, each with 'name' and 'confidence' keys.

    Returns:
        str: a refined and enriched image description generated by the language model.

    """
    
    tag_with_confidence = [f"{tag['name']} ({tag['confidence']:.2f})" for tag in tags]
    prompt = f"""
    You are an image description assistant.
    Here is the raw description of the image: "{description}".
    Here are some tags describing the image with confidence scores: {', '.join(tag_with_confidence)}.
    Please write a natural, detailed and engaging description of the image based on the above information.
    """
    response = openai_client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You improve image descriptions."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.7,
        max_tokens=150
    )
    return response.choices[0].message.content.strip()